name: orchestrator-pipeline-build-LocalDEV
on:
  push:
    branches: [ main ]

jobs:
  #Build Project
  gradle-build:
    name: gradle-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
          cache: 'gradle'
      - name: Setup Gradle 8.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5
      - run: gradle assemble
      - name: upload the build artifact
        uses: actions/upload-artifact@v3
        with:
          name: apache-spark-framework-artifact
          path: build/libs
          retention-days: 1
      - name: Setup caches
        uses: actions/cache@v3
        with:
          path: |
            ~/build/libs
          key: ${{ runner.os }}-build
          restore-keys: |
            ${{ runner.os }}-build

  #Test
  testJUnit:
    name: test-junit
    runs-on: ubuntu-latest
    needs: gradle-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'
      - name: Setup Gradle 8.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5
      - name: Running Unit Tests
        run: gradle check

  #Code Quality
  CodeQuality:
    name: code-quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3    
  #Secrets Detection
  secretDetection:
    name: secret-detection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3        
  # Build Push Docker Image
  buildDockerImage:
     runs-on: ubuntu-latest
     steps:
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: DockerfileDevelop
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/orchestrator-app:latest
